# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SingaporeProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SingaporeProject
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Hero'
  pod 'R.swift'

  target 'SingaporeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SingaporeProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
